# syntax = docker/dockerfile:1

# Adjust NODE_VERSION as desired
ARG NODE_VERSION=24.11.1
FROM node:${NODE_VERSION}-slim AS base

LABEL fly_launch_runtime="Next.js"

# Next.js app lives here
WORKDIR /app

# Set production environment
ENV NODE_ENV="production"
ENV HOSTNAME="0.0.0.0"
ENV PORT="3000"


# Throw-away build stage to reduce size of final image
FROM base AS build

# Build-time Next.js public environment
ARG NEXT_PUBLIC_APPWRITE_PROJECT_ID
ARG NEXT_PUBLIC_APPWRITE_PROJECT_NAME
ARG NEXT_PUBLIC_APPWRITE_ENDPOINT
ARG NEXT_PUBLIC_APPWRITE_ADMIN_TEAM_ID
ARG NEXT_PUBLIC_APPWRITE_DATABASE_ID
ARG NEXT_PUBLIC_APPWRITE_PROJECTS_COLLECTION_ID
ARG NEXT_PUBLIC_APPWRITE_PLATFORM_SETTINGS_COLLECTION_ID
ARG NEXT_PUBLIC_APPWRITE_FEEDBACK_SUBMISSIONS_COLLECTION_ID
ARG NEXT_PUBLIC_APPWRITE_AUDIT_LOGS_COLLECTION_ID
ARG NEXT_PUBLIC_APPWRITE_PROJECT_FEEDBACK_CONFIG_COLLECTION_ID
ARG NEXT_PUBLIC_APPWRITE_PROJECT_ATTENDANCE_CONFIG_COLLECTION_ID
ARG NEXT_PUBLIC_APPWRITE_VOLUNTEER_ATTENDANCE_SESSIONS_COLLECTION_ID
ARG NEXT_PUBLIC_APPWRITE_VOLUNTEER_ATTENDANCE_ENTRIES_COLLECTION_ID
ARG NEXT_PUBLIC_APPWRITE_PROJECT_VOLUNTEER_SETTINGS_COLLECTION_ID
ARG NEXT_PUBLIC_APPWRITE_ATTENDANCE_SIGNATURES_BUCKET_ID

ENV NEXT_PUBLIC_APPWRITE_PROJECT_ID=${NEXT_PUBLIC_APPWRITE_PROJECT_ID}
ENV NEXT_PUBLIC_APPWRITE_PROJECT_NAME=${NEXT_PUBLIC_APPWRITE_PROJECT_NAME}
ENV NEXT_PUBLIC_APPWRITE_ENDPOINT=${NEXT_PUBLIC_APPWRITE_ENDPOINT}
ENV NEXT_PUBLIC_APPWRITE_ADMIN_TEAM_ID=${NEXT_PUBLIC_APPWRITE_ADMIN_TEAM_ID}
ENV NEXT_PUBLIC_APPWRITE_DATABASE_ID=${NEXT_PUBLIC_APPWRITE_DATABASE_ID}
ENV NEXT_PUBLIC_APPWRITE_PROJECTS_COLLECTION_ID=${NEXT_PUBLIC_APPWRITE_PROJECTS_COLLECTION_ID}
ENV NEXT_PUBLIC_APPWRITE_PLATFORM_SETTINGS_COLLECTION_ID=${NEXT_PUBLIC_APPWRITE_PLATFORM_SETTINGS_COLLECTION_ID}
ENV NEXT_PUBLIC_APPWRITE_FEEDBACK_SUBMISSIONS_COLLECTION_ID=${NEXT_PUBLIC_APPWRITE_FEEDBACK_SUBMISSIONS_COLLECTION_ID}
ENV NEXT_PUBLIC_APPWRITE_AUDIT_LOGS_COLLECTION_ID=${NEXT_PUBLIC_APPWRITE_AUDIT_LOGS_COLLECTION_ID}
ENV NEXT_PUBLIC_APPWRITE_PROJECT_FEEDBACK_CONFIG_COLLECTION_ID=${NEXT_PUBLIC_APPWRITE_PROJECT_FEEDBACK_CONFIG_COLLECTION_ID}
ENV NEXT_PUBLIC_APPWRITE_PROJECT_ATTENDANCE_CONFIG_COLLECTION_ID=${NEXT_PUBLIC_APPWRITE_PROJECT_ATTENDANCE_CONFIG_COLLECTION_ID}
ENV NEXT_PUBLIC_APPWRITE_VOLUNTEER_ATTENDANCE_SESSIONS_COLLECTION_ID=${NEXT_PUBLIC_APPWRITE_VOLUNTEER_ATTENDANCE_SESSIONS_COLLECTION_ID}
ENV NEXT_PUBLIC_APPWRITE_VOLUNTEER_ATTENDANCE_ENTRIES_COLLECTION_ID=${NEXT_PUBLIC_APPWRITE_VOLUNTEER_ATTENDANCE_ENTRIES_COLLECTION_ID}
ENV NEXT_PUBLIC_APPWRITE_PROJECT_VOLUNTEER_SETTINGS_COLLECTION_ID=${NEXT_PUBLIC_APPWRITE_PROJECT_VOLUNTEER_SETTINGS_COLLECTION_ID}
ENV NEXT_PUBLIC_APPWRITE_ATTENDANCE_SIGNATURES_BUCKET_ID=${NEXT_PUBLIC_APPWRITE_ATTENDANCE_SIGNATURES_BUCKET_ID}

# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential node-gyp pkg-config python-is-python3

# Install node modules
COPY package-lock.json package.json ./
RUN npm ci --include=dev

# Copy application code
COPY . .

# Build application
RUN npx next build

# Remove development dependencies
RUN npm prune --omit=dev


# Final stage for app image
FROM base

# Copy built application
COPY --from=build /app /app

# Entrypoint sets up the container.
ENTRYPOINT [ "/app/docker-entrypoint.js" ]

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD [ "npm", "run", "start" ]
