#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

DRY_RUN=0
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=1
fi

if [[ -f .env ]]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

if [[ -f .env.local ]]; then
  set -a
  # shellcheck disable=SC1091
  source .env.local
  set +a
fi

FLYCTL_BIN="${FLYCTL_BIN:-$(command -v flyctl || true)}"
if [[ -z "$FLYCTL_BIN" ]]; then
  echo "flyctl is not installed or not in PATH." >&2
  exit 1
fi

FLY_APP="${FLY_APP:-$(awk -F"'" '/^app = / { print $2; exit }' fly.toml)}"
if [[ -z "$FLY_APP" ]]; then
  echo "Could not determine Fly app name from fly.toml." >&2
  exit 1
fi

RUNTIME_VARS=(
  APPWRITE_PROJECT_ID
  APPWRITE_API_KEY
  APPWRITE_ENDPOINT
  WAITWHILE_API_KEY
  NEXT_PUBLIC_APPWRITE_PROJECT_ID
  NEXT_PUBLIC_APPWRITE_PROJECT_NAME
  NEXT_PUBLIC_APPWRITE_ENDPOINT
  NEXT_PUBLIC_APPWRITE_ADMIN_TEAM_ID
  NEXT_PUBLIC_APPWRITE_DATABASE_ID
  NEXT_PUBLIC_APPWRITE_PROJECTS_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_PLATFORM_SETTINGS_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_FEEDBACK_SUBMISSIONS_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_AUDIT_LOGS_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_PROJECT_FEEDBACK_CONFIG_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_PROJECT_ATTENDANCE_CONFIG_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_VOLUNTEER_ATTENDANCE_SESSIONS_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_VOLUNTEER_ATTENDANCE_ENTRIES_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_PROJECT_VOLUNTEER_SETTINGS_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_ATTENDANCE_SIGNATURES_BUCKET_ID
  AUTH0_SECRET
  APP_BASE_URL
  AUTH0_DOMAIN
  AUTH0_CLIENT_ID
  AUTH0_CLIENT_SECRET
)

BUILD_VARS=(
  NEXT_PUBLIC_APPWRITE_PROJECT_ID
  NEXT_PUBLIC_APPWRITE_PROJECT_NAME
  NEXT_PUBLIC_APPWRITE_ENDPOINT
  NEXT_PUBLIC_APPWRITE_ADMIN_TEAM_ID
  NEXT_PUBLIC_APPWRITE_DATABASE_ID
  NEXT_PUBLIC_APPWRITE_PROJECTS_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_PLATFORM_SETTINGS_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_FEEDBACK_SUBMISSIONS_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_AUDIT_LOGS_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_PROJECT_FEEDBACK_CONFIG_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_PROJECT_ATTENDANCE_CONFIG_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_VOLUNTEER_ATTENDANCE_SESSIONS_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_VOLUNTEER_ATTENDANCE_ENTRIES_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_PROJECT_VOLUNTEER_SETTINGS_COLLECTION_ID
  NEXT_PUBLIC_APPWRITE_ATTENDANCE_SIGNATURES_BUCKET_ID
)

SECRET_ARGS=()
SECRET_NAMES=()
for key in "${RUNTIME_VARS[@]}"; do
  value="${!key-}"
  if [[ -n "$value" ]]; then
    SECRET_ARGS+=("${key}=${value}")
    SECRET_NAMES+=("$key")
  fi
done

BUILD_ARGS=()
BUILD_NAMES=()
for key in "${BUILD_VARS[@]}"; do
  value="${!key-}"
  if [[ -n "$value" ]]; then
    BUILD_ARGS+=("--build-arg" "${key}=${value}")
    BUILD_NAMES+=("$key")
  fi
done

if (( ${#SECRET_ARGS[@]} == 0 )); then
  echo "No Fly secrets were resolved from .env/.env.local." >&2
  exit 1
fi

echo "Fly app: $FLY_APP"
echo "Runtime vars to sync: ${SECRET_NAMES[*]}"
echo "Build args to pass: ${BUILD_NAMES[*]}"

if (( DRY_RUN == 1 )); then
  exit 0
fi

"$FLYCTL_BIN" secrets set --stage --app "$FLY_APP" "${SECRET_ARGS[@]}"
"$FLYCTL_BIN" deploy --app "$FLY_APP" "${BUILD_ARGS[@]}"
